            - name: Publish Dart/Flutter package - latest flutter
  # You may pin to the exact commit or the version.
  # uses: afonsocraposo/actions-flutter-pub-publisher@7d56c3b0371352fb162ecd029b7ae978f8992217
  uses: afonsocraposo/actions-flutter-pub-publisher@v1.1.0
  with:
    # Google Account credential
    credential: 
    # (Optional) Publish packages type. (default: true)
    flutter_package: # optional, default is true
    # (Optional) Skip test (default: false)
    skip_test: # optional
    # (Optional) Package directory (default: ".")
    package_directory: # optional, default is .
    # (Optional) Dry run, no publish (default: false)
    dry_run: # optional
          
